// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFuWQdChxpvXSbTMqcU25wE4s664uhtaE',
    appId: '1:852568791430:web:1e737a36b2dbc325d03407',
    messagingSenderId: '852568791430',
    projectId: 'last-640c7',
    authDomain: 'last-640c7.firebaseapp.com',
    storageBucket: 'last-640c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyB3_HQJK6qVTqxM_Fpua1odTY9YRXuKg',
    appId: '1:852568791430:android:31d4320e355669fcd03407',
    messagingSenderId: '852568791430',
    projectId: 'last-640c7',
    storageBucket: 'last-640c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNNDbvGDGG4rAZjfEWrE6p8q1AhXgZhlc',
    appId: '1:852568791430:ios:b1665f8c69538874d03407',
    messagingSenderId: '852568791430',
    projectId: 'last-640c7',
    storageBucket: 'last-640c7.appspot.com',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNNDbvGDGG4rAZjfEWrE6p8q1AhXgZhlc',
    appId: '1:852568791430:ios:b1665f8c69538874d03407',
    messagingSenderId: '852568791430',
    projectId: 'last-640c7',
    storageBucket: 'last-640c7.appspot.com',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFuWQdChxpvXSbTMqcU25wE4s664uhtaE',
    appId: '1:852568791430:web:9ab471724f8cad17d03407',
    messagingSenderId: '852568791430',
    projectId: 'last-640c7',
    authDomain: 'last-640c7.firebaseapp.com',
    storageBucket: 'last-640c7.appspot.com',
  );
}
